const ACTION_TYPES = {
    CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',
    UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
    DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
    GET_ALL_DEPARTMENTS: 'GET_ALL_DEPARTMENTS',
    CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    GET_ALL_EMPLOYEES: 'GET_ALL_EMPLOYEES'
}
export default ACTION_TYPES