name: Build and deploy .NET Core app to Windows WebApp azup-ibm-test-api
on:
  push:
    paths-ignore:
    - 'up-task-gts-react-app/**'
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: azup-ibm-test-api
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.azup_ibm_test_api_7187 }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY: .
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}\\up-task-api"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}\\up-task-api" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}\\up-task-api" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}\\up-task-api" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
